plugins {
    id 'java'
    // Spring Boot 3.4.0 manages Spring Framework to 6.2.0
    id 'org.springframework.boot' version '3.4.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

repositories {
    mavenCentral()
}

dependencies {
    // Root Dependency
    // This pulls in spring-tx and spring-core transitively
    implementation 'com.arangodb:arangodb-spring-data:4.5.0'
    
    // Standard Starters
    implementation 'org.springframework.boot:spring-boot-starter-web'
}
