dependencies {
    // Before: implementation 'org.apache.logging.log4j:log4j-core:2.14.1'
    implementation libs.apache.log4j.core
    implementation libs.apache.log4j.api
    
    // Before: implementation 'org.apache.struts:struts2-core:2.3.37'
    implementation libs.apache.struts.core
    
    // Before: implementation 'commons-collections:commons-collections:3.2.1'
    implementation libs.apache.commons.collections

    testImplementation libs.junit
}
