[versions]
# Define versions here
log4j = "2.14.1"
struts = "2.3.37"
commons-collections = "3.2.2"
junit = "4.12"

[libraries]
# Define the actual dependencies using the versions above
apache-log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
apache-log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
apache-struts-core = { group = "org.apache.struts", name = "struts2-core", version.ref = "struts" }
apache-commons-collections = { group = "commons-collections", name = "commons-collections", version.ref = "commons-collections" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
# You can also define plugins here if needed
# example-plugin = { id = "com.github.ben-manes.versions", version = "0.42.0" }
